export const RESTORE_TOKEN = "RESTORE_TOKEN";
export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const SET_COORDINATE = "SET_COORDINATE";
export const GET_SUB_SALE = "GET_SUB_SALE";
export const GET_SUB_RENT = "GET_SUB_RENT";
export const GET_PROP_BYCOOR = "GET_PROP_BYCOOR";
export const GET_SALE_PROPERTY = "GET_SALE_PROPERTY";
export const GET_RENT_PROPERTY = "GET_RENT_PROPERTY";
export const GET_MY_PROPERTY = "GET_MY_PROPERTY";
export const DELETE_MY_PROPERTY = "DELETE_MY_PROPERTY";

